-- ============================================================
-- UndosaTech — OMOP CDM v5.4 schema (PostgreSQL / Supabase)
-- Adapted from the OHDSI CommonDataModel v5.4 DDL, plus the
-- Medical Imaging (MI-CDM) extension tables used for
-- ophthalmic / neuro imaging harmonisation.
-- Run in the Supabase SQL Editor.
-- ============================================================

create schema if not exists omop;

-- ── Standardised vocabulary (minimal working set) ─────────────
create table if not exists omop.vocabulary (
    vocabulary_id         varchar(20)  primary key,
    vocabulary_name       varchar(255) not null,
    vocabulary_reference  varchar(255),
    vocabulary_version    varchar(255),
    vocabulary_concept_id integer      not null default 0
);

create table if not exists omop.concept (
    concept_id       integer      primary key,
    concept_name     varchar(255) not null,
    domain_id        varchar(20)  not null,
    vocabulary_id    varchar(20)  not null,
    concept_class_id varchar(20)  not null,
    standard_concept varchar(1),
    concept_code     varchar(50)  not null,
    valid_start_date date         not null default '1970-01-01',
    valid_end_date   date         not null default '2099-12-31',
    invalid_reason   varchar(1)
);

create table if not exists omop.concept_relationship (
    concept_id_1     integer     not null,
    concept_id_2     integer     not null,
    relationship_id  varchar(20) not null,
    valid_start_date date        not null default '1970-01-01',
    valid_end_date   date        not null default '2099-12-31',
    invalid_reason   varchar(1),
    primary key (concept_id_1, concept_id_2, relationship_id)
);

create table if not exists omop.concept_ancestor (
    ancestor_concept_id      integer not null,
    descendant_concept_id    integer not null,
    min_levels_of_separation integer not null,
    max_levels_of_separation integer not null,
    primary key (ancestor_concept_id, descendant_concept_id)
);

-- ── Health system tables ──────────────────────────────────────
create table if not exists omop.location (
    location_id   integer primary key generated by default as identity,
    address_1     varchar(50),
    address_2     varchar(50),
    city          varchar(50),
    state         varchar(2),
    zip           varchar(9),
    county        varchar(20),
    location_source_value varchar(50),
    country_concept_id    integer,
    country_source_value  varchar(80),
    latitude      numeric,
    longitude     numeric
);

create table if not exists omop.care_site (
    care_site_id                integer primary key generated by default as identity,
    care_site_name              varchar(255),
    place_of_service_concept_id integer,
    location_id                 integer references omop.location(location_id),
    care_site_source_value      varchar(50),
    place_of_service_source_value varchar(50)
);

create table if not exists omop.provider (
    provider_id         integer primary key generated by default as identity,
    provider_name       varchar(255),
    npi                 varchar(20),
    dea                 varchar(20),
    specialty_concept_id integer,
    care_site_id        integer references omop.care_site(care_site_id),
    year_of_birth       integer,
    gender_concept_id   integer,
    provider_source_value varchar(50),
    specialty_source_value varchar(50),
    specialty_source_concept_id integer,
    gender_source_value varchar(50),
    gender_source_concept_id integer
);

-- ── Clinical data tables ──────────────────────────────────────
create table if not exists omop.person (
    person_id                   bigint primary key generated by default as identity,
    gender_concept_id           integer     not null,
    year_of_birth               integer     not null,
    month_of_birth              integer,
    day_of_birth                integer,
    birth_datetime              timestamp,
    race_concept_id             integer     not null default 0,
    ethnicity_concept_id        integer     not null default 0,
    location_id                 integer references omop.location(location_id),
    provider_id                 integer references omop.provider(provider_id),
    care_site_id                integer references omop.care_site(care_site_id),
    person_source_value         varchar(50),
    gender_source_value         varchar(50),
    gender_source_concept_id    integer,
    race_source_value           varchar(50),
    race_source_concept_id      integer,
    ethnicity_source_value      varchar(50),
    ethnicity_source_concept_id integer
);

create table if not exists omop.observation_period (
    observation_period_id         bigint primary key generated by default as identity,
    person_id                     bigint  not null references omop.person(person_id),
    observation_period_start_date date    not null,
    observation_period_end_date   date    not null,
    period_type_concept_id        integer not null
);

create table if not exists omop.visit_occurrence (
    visit_occurrence_id           bigint primary key generated by default as identity,
    person_id                     bigint  not null references omop.person(person_id),
    visit_concept_id              integer not null,
    visit_start_date              date    not null,
    visit_start_datetime          timestamp,
    visit_end_date                date    not null,
    visit_end_datetime            timestamp,
    visit_type_concept_id         integer not null,
    provider_id                   integer,
    care_site_id                  integer,
    visit_source_value            varchar(50),
    visit_source_concept_id       integer,
    admitted_from_concept_id      integer,
    admitted_from_source_value    varchar(50),
    discharged_to_concept_id      integer,
    discharged_to_source_value    varchar(50),
    preceding_visit_occurrence_id bigint
);

create table if not exists omop.condition_occurrence (
    condition_occurrence_id       bigint primary key generated by default as identity,
    person_id                     bigint  not null references omop.person(person_id),
    condition_concept_id          integer not null,
    condition_start_date          date    not null,
    condition_start_datetime      timestamp,
    condition_end_date            date,
    condition_end_datetime        timestamp,
    condition_type_concept_id     integer not null,
    condition_status_concept_id   integer,
    stop_reason                   varchar(20),
    provider_id                   integer,
    visit_occurrence_id           bigint references omop.visit_occurrence(visit_occurrence_id),
    visit_detail_id               bigint,
    condition_source_value        varchar(50),
    condition_source_concept_id   integer,
    condition_status_source_value varchar(50)
);

create table if not exists omop.drug_exposure (
    drug_exposure_id             bigint primary key generated by default as identity,
    person_id                    bigint  not null references omop.person(person_id),
    drug_concept_id              integer not null,
    drug_exposure_start_date     date    not null,
    drug_exposure_start_datetime timestamp,
    drug_exposure_end_date       date    not null,
    drug_exposure_end_datetime   timestamp,
    verbatim_end_date            date,
    drug_type_concept_id         integer not null,
    stop_reason                  varchar(20),
    refills                      integer,
    quantity                     numeric,
    days_supply                  integer,
    sig                          text,
    route_concept_id             integer,
    lot_number                   varchar(50),
    provider_id                  integer,
    visit_occurrence_id          bigint references omop.visit_occurrence(visit_occurrence_id),
    visit_detail_id              bigint,
    drug_source_value            varchar(50),
    drug_source_concept_id       integer,
    route_source_value           varchar(50),
    dose_unit_source_value       varchar(50)
);

create table if not exists omop.procedure_occurrence (
    procedure_occurrence_id     bigint primary key generated by default as identity,
    person_id                   bigint  not null references omop.person(person_id),
    procedure_concept_id        integer not null,
    procedure_date              date    not null,
    procedure_datetime          timestamp,
    procedure_end_date          date,
    procedure_end_datetime      timestamp,
    procedure_type_concept_id   integer not null,
    modifier_concept_id         integer,
    quantity                    integer,
    provider_id                 integer,
    visit_occurrence_id         bigint references omop.visit_occurrence(visit_occurrence_id),
    visit_detail_id             bigint,
    procedure_source_value      varchar(50),
    procedure_source_concept_id integer,
    modifier_source_value       varchar(50)
);

create table if not exists omop.device_exposure (
    device_exposure_id             bigint primary key generated by default as identity,
    person_id                      bigint  not null references omop.person(person_id),
    device_concept_id              integer not null,
    device_exposure_start_date     date    not null,
    device_exposure_start_datetime timestamp,
    device_exposure_end_date       date,
    device_exposure_end_datetime   timestamp,
    device_type_concept_id         integer not null,
    unique_device_id               varchar(255),
    production_id                  varchar(255),
    quantity                       integer,
    provider_id                    integer,
    visit_occurrence_id            bigint references omop.visit_occurrence(visit_occurrence_id),
    visit_detail_id                bigint,
    device_source_value            varchar(50),
    device_source_concept_id       integer,
    unit_concept_id                integer,
    unit_source_value              varchar(50),
    unit_source_concept_id         integer
);

create table if not exists omop.measurement (
    measurement_id                bigint primary key generated by default as identity,
    person_id                     bigint  not null references omop.person(person_id),
    measurement_concept_id        integer not null,
    measurement_date              date    not null,
    measurement_datetime          timestamp,
    measurement_time              varchar(10),
    measurement_type_concept_id   integer not null,
    operator_concept_id           integer,
    value_as_number               numeric,
    value_as_concept_id           integer,
    unit_concept_id               integer,
    range_low                     numeric,
    range_high                    numeric,
    provider_id                   integer,
    visit_occurrence_id           bigint references omop.visit_occurrence(visit_occurrence_id),
    visit_detail_id               bigint,
    measurement_source_value      varchar(50),
    measurement_source_concept_id integer,
    unit_source_value             varchar(50),
    unit_source_concept_id        integer,
    value_source_value            varchar(50),
    measurement_event_id          bigint,
    meas_event_field_concept_id   integer
);

create table if not exists omop.observation (
    observation_id                bigint primary key generated by default as identity,
    person_id                     bigint  not null references omop.person(person_id),
    observation_concept_id        integer not null,
    observation_date              date    not null,
    observation_datetime          timestamp,
    observation_type_concept_id   integer not null,
    value_as_number               numeric,
    value_as_string               varchar(60),
    value_as_concept_id           integer,
    qualifier_concept_id          integer,
    unit_concept_id               integer,
    provider_id                   integer,
    visit_occurrence_id           bigint references omop.visit_occurrence(visit_occurrence_id),
    visit_detail_id               bigint,
    observation_source_value      varchar(50),
    observation_source_concept_id integer,
    unit_source_value             varchar(50),
    qualifier_source_value        varchar(50),
    value_source_value            varchar(50),
    observation_event_id          bigint,
    obs_event_field_concept_id    integer
);

create table if not exists omop.death (
    person_id               bigint primary key references omop.person(person_id),
    death_date              date    not null,
    death_datetime          timestamp,
    death_type_concept_id   integer,
    cause_concept_id        integer,
    cause_source_value      varchar(50),
    cause_source_concept_id integer
);

-- ── Medical Imaging extension (MI-CDM) ────────────────────────
-- OHDSI Medical Imaging workgroup extension: links DICOM studies
-- and derived image features to the clinical event tables.
create table if not exists omop.image_occurrence (
    image_occurrence_id     bigint primary key generated by default as identity,
    person_id               bigint  not null references omop.person(person_id),
    procedure_occurrence_id bigint references omop.procedure_occurrence(procedure_occurrence_id),
    visit_occurrence_id     bigint references omop.visit_occurrence(visit_occurrence_id),
    anatomic_site_concept_id integer,
    wadors_uri              text,
    local_path              text,
    image_occurrence_date   date not null,
    image_study_uid         varchar(250) not null,
    image_series_uid        varchar(250),
    modality_concept_id     integer,
    modality_source_value   varchar(50)   -- e.g. OPT (OCT), OP (fundus), MR, CT
);

create table if not exists omop.image_feature (
    image_feature_id             bigint primary key generated by default as identity,
    person_id                    bigint  not null references omop.person(person_id),
    image_occurrence_id          bigint  not null references omop.image_occurrence(image_occurrence_id),
    image_feature_event_id       bigint,
    image_feature_event_field_concept_id integer,
    image_feature_concept_id     integer not null,
    image_feature_type_concept_id integer not null,
    image_finding_concept_id     integer,
    image_finding_num            numeric,
    anatomic_site_concept_id     integer,
    alg_system                   varchar(255),   -- algorithm / model that produced the feature
    alg_datetime                 timestamp
);

-- ── Indexes ───────────────────────────────────────────────────
create index if not exists idx_person_gender          on omop.person (gender_concept_id);
create index if not exists idx_obs_period_person      on omop.observation_period (person_id);
create index if not exists idx_visit_person           on omop.visit_occurrence (person_id, visit_start_date);
create index if not exists idx_condition_person       on omop.condition_occurrence (person_id, condition_concept_id);
create index if not exists idx_condition_concept      on omop.condition_occurrence (condition_concept_id);
create index if not exists idx_drug_person            on omop.drug_exposure (person_id, drug_concept_id);
create index if not exists idx_procedure_person       on omop.procedure_occurrence (person_id, procedure_concept_id);
create index if not exists idx_measurement_person     on omop.measurement (person_id, measurement_concept_id);
create index if not exists idx_measurement_concept    on omop.measurement (measurement_concept_id);
create index if not exists idx_observation_person     on omop.observation (person_id, observation_concept_id);
create index if not exists idx_image_occ_person       on omop.image_occurrence (person_id);
create index if not exists idx_image_occ_study_uid    on omop.image_occurrence (image_study_uid);
create index if not exists idx_image_feature_occ      on omop.image_feature (image_occurrence_id);
create index if not exists idx_concept_code           on omop.concept (concept_code, vocabulary_id);
create index if not exists idx_concept_domain         on omop.concept (domain_id, standard_concept);

-- ── Seed vocabulary rows used by the FHIR adapter ─────────────
insert into omop.vocabulary (vocabulary_id, vocabulary_name, vocabulary_reference, vocabulary_version)
values
    ('SNOMED',  'Systematic Nomenclature of Medicine - Clinical Terms', 'http://snomed.info/sct', '2025'),
    ('LOINC',   'Logical Observation Identifiers Names and Codes',      'http://loinc.org',        '2.78'),
    ('RxNorm',  'RxNorm',                                               'http://www.nlm.nih.gov/research/umls/rxnorm', '2025'),
    ('Gender',  'OMOP Gender',                                          'OMOP generated',          '5.4'),
    ('DICOM',   'Digital Imaging and Communications in Medicine',       'https://www.dicomstandard.org', '2025')
on conflict (vocabulary_id) do nothing;

insert into omop.concept (concept_id, concept_name, domain_id, vocabulary_id, concept_class_id, standard_concept, concept_code)
values
    (8507, 'MALE',   'Gender', 'Gender', 'Gender', 'S', 'M'),
    (8532, 'FEMALE', 'Gender', 'Gender', 'Gender', 'S', 'F'),
    (0,    'No matching concept', 'Metadata', 'None', 'Undefined', null, 'No matching concept')
on conflict (concept_id) do nothing;

-- ── Security: RLS on all OMOP tables (service role writes) ────
do $$
declare t record;
begin
    for t in select tablename from pg_tables where schemaname = 'omop' loop
        execute format('alter table omop.%I enable row level security', t.tablename);
        execute format('drop policy if exists "omop read for authenticated" on omop.%I', t.tablename);
        execute format(
            'create policy "omop read for authenticated" on omop.%I for select to authenticated using (true)',
            t.tablename
        );
    end loop;
end $$;

grant usage on schema omop to authenticated, service_role;
grant select on all tables in schema omop to authenticated;
grant all on all tables in schema omop to service_role;
alter default privileges in schema omop grant select on tables to authenticated;
