-- ============================================================
-- UndosaTech: Persistent Study Storage (Priority 4)
-- Run in Supabase SQL Editor AFTER the fl_nodes migration
-- ============================================================

-- ── Studies ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS studies (
    id TEXT PRIMARY KEY,                        -- UUID generated by FastAPI
    
    -- Ownership
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    user_email TEXT,                            -- denormalised for admin queries

    -- Configuration (immutable after launch)
    name TEXT NOT NULL,
    model TEXT NOT NULL,                        -- ResNet-18, EfficientNet-B0, etc.
    dataset TEXT NOT NULL,                      -- PathMNIST, ChestMNIST, etc.
    num_rounds INTEGER NOT NULL DEFAULT 5,
    nodes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],   -- node_ids participating

    -- Differential privacy (null = disabled, ready for Priority 2)
    dp_enabled BOOLEAN DEFAULT FALSE,
    dp_epsilon NUMERIC,
    dp_delta NUMERIC,
    dp_noise_multiplier NUMERIC,

    -- Status lifecycle
    -- queued → running → completed | failed | stopped
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'completed', 'failed', 'stopped')),
    
    -- Progress
    current_round INTEGER DEFAULT 0,
    total_rounds INTEGER,
    progress_pct NUMERIC GENERATED ALWAYS AS (
        CASE WHEN total_rounds > 0
             THEN ROUND((current_round::NUMERIC / total_rounds) * 100, 1)
             ELSE 0 END
    ) STORED,

    -- Results (written on completion)
    final_accuracy NUMERIC,
    final_loss NUMERIC,
    per_class_accuracy JSONB,                  -- { "class_0": 0.91, ... }
    model_download_path TEXT,                  -- Railway path to .pth file

    -- Failure info
    error_message TEXT,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Training logs ─────────────────────────────────────────────────────────────
-- Separate table: logs are written every few seconds during training.
-- Keeping them out of studies avoids row bloat and makes polling fast.

CREATE TABLE IF NOT EXISTS study_logs (
    id BIGSERIAL PRIMARY KEY,
    study_id TEXT NOT NULL REFERENCES studies(id) ON DELETE CASCADE,
    round_number INTEGER,
    logged_at TIMESTAMPTZ DEFAULT NOW(),
    level TEXT DEFAULT 'info'                  -- info | warning | error
        CHECK (level IN ('info', 'warning', 'error')),
    message TEXT NOT NULL,
    metrics JSONB                              -- { accuracy, loss, node_id, ... }
);

-- ── Round metrics (one row per FL round, for charting) ────────────────────────

CREATE TABLE IF NOT EXISTS study_rounds (
    id BIGSERIAL PRIMARY KEY,
    study_id TEXT NOT NULL REFERENCES studies(id) ON DELETE CASCADE,
    round_number INTEGER NOT NULL,
    recorded_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Aggregated metrics across all nodes
    accuracy NUMERIC,
    loss NUMERIC,
    val_accuracy NUMERIC,
    val_loss NUMERIC,
    
    -- Per-node breakdown
    node_metrics JSONB,                        -- { "node_id": { accuracy, loss, samples } }
    
    UNIQUE (study_id, round_number)
);

-- ── Triggers ──────────────────────────────────────────────────────────────────

CREATE OR REPLACE TRIGGER studies_updated_at
    BEFORE UPDATE ON studies
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();
-- Note: update_updated_at() was created in the fl_nodes migration.
-- If running this standalone, add:
-- CREATE OR REPLACE FUNCTION update_updated_at() RETURNS trigger AS $$
-- BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$ LANGUAGE plpgsql;

-- Auto-clean logs older than 30 days (keep recent studies fast)
CREATE OR REPLACE FUNCTION delete_old_study_logs() RETURNS trigger AS $$
BEGIN
    DELETE FROM study_logs
    WHERE logged_at < NOW() - INTERVAL '30 days';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER cleanup_study_logs
    AFTER INSERT ON study_logs
    FOR EACH ROW EXECUTE FUNCTION delete_old_study_logs();

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_studies_user_id     ON studies(user_id);
CREATE INDEX IF NOT EXISTS idx_studies_status      ON studies(status);
CREATE INDEX IF NOT EXISTS idx_studies_created_at  ON studies(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_study_logs_study_id ON study_logs(study_id);
CREATE INDEX IF NOT EXISTS idx_study_logs_logged_at ON study_logs(logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_study_rounds_study  ON study_rounds(study_id, round_number);

-- ── Row Level Security ────────────────────────────────────────────────────────

ALTER TABLE studies      ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_logs   ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_rounds ENABLE ROW LEVEL SECURITY;

-- Users can only see/modify their own studies
CREATE POLICY "users_own_studies"
    ON studies FOR ALL
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "users_own_study_logs"
    ON study_logs FOR SELECT
    TO authenticated
    USING (
        study_id IN (
            SELECT id FROM studies WHERE user_id = auth.uid()
        )
    );

CREATE POLICY "users_own_study_rounds"
    ON study_rounds FOR SELECT
    TO authenticated
    USING (
        study_id IN (
            SELECT id FROM studies WHERE user_id = auth.uid()
        )
    );

-- Service role (FastAPI backend) can do everything
CREATE POLICY "service_role_studies"
    ON studies FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE POLICY "service_role_study_logs"
    ON study_logs FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE POLICY "service_role_study_rounds"
    ON study_rounds FOR ALL TO service_role
    USING (true) WITH CHECK (true);

-- ── Useful views ──────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW studies_summary AS
SELECT
    s.id,
    s.user_id,
    s.user_email,
    s.name,
    s.model,
    s.dataset,
    s.status,
    s.current_round,
    s.total_rounds,
    s.progress_pct,
    s.final_accuracy,
    s.dp_enabled,
    s.nodes,
    s.created_at,
    s.started_at,
    s.completed_at,
    EXTRACT(EPOCH FROM (COALESCE(s.completed_at, NOW()) - s.started_at))::INTEGER AS duration_seconds,
    (SELECT COUNT(*) FROM study_logs l WHERE l.study_id = s.id) AS log_count
FROM studies s;

COMMENT ON TABLE studies IS 'Federated learning study configurations and results. One row per study, scoped per user.';
COMMENT ON TABLE study_logs IS 'Training log lines per study. High-write; auto-cleaned after 30 days.';
COMMENT ON TABLE study_rounds IS 'Per-round aggregated metrics for charting training progress.';
